import fs from "node:fs";

console.log("");
console.log("================================================");
console.log("          ATTESTGUARD JUDGE DEMO");
console.log("  (reads artifacts/underwriting-report.json,");
console.log("   generated by `npm run report` from real");
console.log("   evaluateAdvancePolicy/underwrite output)");
console.log("================================================");

const reportPath = "artifacts/underwriting-report.json";

if (!fs.existsSync(reportPath)) {
  console.error("Missing underwriting report. Run: npm run report");
  process.exit(1);
}

const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));

console.log("");
console.log("DECISION:");
console.log(`Outcome: ${report.summary.outcome}`);
console.log(`Risk tier: ${report.summary.riskTier}`);

console.log("");
console.log("DETERMINISTIC POLICY ENGINE:");
console.log(`Verdict: ${report.policy.verdict}`);
console.log(`Reason: ${report.policy.reason}`);

console.log("");
console.log("BOUNDED AI UNDERWRITING:");
console.log(`Recommendation: ${report.ai.recommendation}`);
console.log(`Review required: ${report.review.required}`);

console.log("");
console.log("INTEGRITY (real hashes, computed by generate-report.ts):");
console.log(`Decision hash: ${report.integrity.decisionHash}`);
console.log(`Evidence hash: ${report.integrity.evidenceHash}`);
console.log(`AI trace hash: ${report.integrity.aiTraceHash}`);

console.log("");
console.log("FINAL STATUS:");
console.log(report.review.required ? "REVIEW_REQUIRED - fundAdvanceFromQuery is not called" : report.summary.outcome);

console.log("");
console.log("================================================");
console.log(" Demo displays generated artifacts. It does not claim unperformed verification.");
console.log("================================================");